name: build

on:
  push:
    branches:
      - 'main'

jobs:
  dockerhub-build-push:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.date.outputs.date }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository }}:0.30.1
